output_dir: ~/scratch/protein_output
output_file: ~/scratch/protein-datasets/5V/GearNetIEConv.pkl

dataset:
  class: V5
  path: ~/scratch/protein-datasets/5V
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
    - class: ProteinView
      view: residue

task:
  class: PropertyPrediction
  num_mlp_layer: 3
  mlp_batch_norm: True
  mlp_dropout: 0.5
  model:
    class: GearNetIEConv
    input_dim: 21
    embedding_dim: 512
    hidden_dims: [512, 512, 512, 512, 512, 512]
    batch_norm: True
    concat_hidden: True
    short_cut: True
    readout: 'sum'
    num_relation: 7
    edge_input_dim: 59
    num_angle_bin: 8
    layer_norm: True
    dropout: 0.2
    use_ieconv: True
  graph_construction_model:
    class: GraphConstruction
    node_layers:
      - class: AlphaCarbonNode
    edge_layers:
      - class: SequentialEdge
        max_distance: 2
      - class: SpatialEdge
        radius: 10.0
        min_distance: 5
      - class: KNNEdge
        k: 10
        min_distance: 5
    edge_feature: gearnet
  criterion: ce
  metric: ['acc']
  num_class: 1195

gpus: [0]
batch_size: 2

model_checkpoint: ~/scratch/protein-model-weights/gearnet-model-weights/fold_mc_gearnet_edge_ieconv.pth