output_dir: ~/scratch/protein_output
output_file: ~/scratch/protein-datasets/5V/GearNetEdge.pkl

dataset:
  class: V5
  path: ~/scratch/protein-datasets/5V
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
    - class: ProteinView
      view: residue

task:
  class: MultipleBinaryClassification
  model:
    class: GearNet
    input_dim: 21
    hidden_dims: [512, 512, 512, 512, 512, 512]
    batch_norm: True
    concat_hidden: True
    short_cut: True
    readout: 'sum'
    num_relation: 7
    edge_input_dim: 59
    num_angle_bin: 8
  graph_construction_model:
    class: GraphConstruction
    node_layers:
      - class: AlphaCarbonNode
    edge_layers:
      - class: SequentialEdge
        max_distance: 2
      - class: SpatialEdge
        radius: 10.0
        min_distance: 5
      - class: KNNEdge
        k: 10
        min_distance: 5
    edge_feature: gearnet
  criterion: bce
  num_mlp_layer: 3
  metric: ['auprc@micro', 'f1_max']


gpus: [0]
batch_size: 2

checkpoint: ~/scratch/protein_output/MultipleBinaryClassification/EnzymeCommission/GearNet/2023-01-31-20-14-48/model_epoch_94.pth