output_dir: ~/scratch/jingao/Protein-Activity-Prediction/output

dataset:
  class: V5
  path: ~/scratch/jingao/Protein-Activity-Prediction/data/20230927_2k
  atom_feature: null
  bond_feature: null
  split_ratio: [0.8, 0.1, 0.1]
  transform:
    class: ProteinView
    view: residue

task:
  class: PropertyPrediction
  model:
    class: FusionNetwork
    sequence_model:
      class: ESM
      path: ~/.cache/torch/hub/checkpoints
      model: ESM-2-650M
    structure_model:
      class: GearNet
      input_dim: 1280
      hidden_dims: [512, 512, 512, 512, 512, 512]
      batch_norm: True
      concat_hidden: True
      short_cut: True
      readout: 'sum'
      num_relation: 7
      edge_input_dim: 59
      num_angle_bin: 8
  graph_construction_model:
    class: GraphConstruction
    node_layers:
      - class: AlphaCarbonNode
    edge_layers:
      - class: SequentialEdge
        max_distance: 2
      - class: SpatialEdge
        radius: 10.0
        min_distance: 5
      - class: KNNEdge
        k: 10
        min_distance: 5
    edge_feature: gearnet
  criterion: mse
  metric: ['mae', 'rmse', 'spearmanr', 'pearsonr']
  num_mlp_layer: 3

optimizer:
  class: Adam
  lr: 1.0e-4

engine:
  gpus: [0]
  batch_size: 4
  log_interval: 1000

sequence_model_lr_ratio: 0.1

metric: spearmanr [activity]

train:
  num_epoch: 20